import React from 'react';
import Head from 'next/head';
import Skeleton_StoryCard from '../../components/Skeletons/Skeleton_StoryCard/Skeleton_StoryCard';
import { useQuery } from '@apollo/client';
import { GET_ALL_STORIES, GET_TRAVELER } from '../../services';
import { StoryCard, StoryWidget, Categories, Welcome } from '../../components';
import { Layout } from '../../components';

export default function HomePage({stories, traveler}) {

    console.log(stories)

    return (
        <Layout>
            <div className="container mx-auto px-10 mb-8">
                <Head>
                    <title>My Travel Story App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
                    <div className='col-span-1 lg:col-span-8'>
                        {stories? (
                        stories.map((story) => (
                            <StoryCard story={story} traveler={traveler} key={story.title} />
                        )
                        ))
                        : (
                            <Skeleton_StoryCard />
                        )
                        }
                    </div>
                    <div className='col-span-1 lg:col-span-4'>
                        <div>
                            <Welcome />
                            <StoryWidget />
                            <Categories />
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    )
}

export async function getStaticProps() {
    const stories = (await GET_ALL_STORIES()) || [];
    const traveler = (await GET_TRAVELER()) || [];

        return {
            props: {
                stories, traveler
            }
    }
}
