import React from 'react';
import Head from 'next/head';
import Skeleton_StoryCard from '../../components/Skeletons/Skeleton_StoryCard/Skeleton_StoryCard';
import {getStories} from '../../services';
import { StoryCard, StoryWidget, Categories, Profile } from '../../components';
import { Layout } from '../../components';

export default function HomePage({ stories }) {
console.log(stories)
  return (
        <Layout>
            <div className="container mx-auto px-10 mb-8">
                <Head>
                    <title>My Travel Story App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
                    <div className='col-span-1 lg:col-span-8'>
                        {stories? (
                        stories.map((story) => (
                            <StoryCard story={story.node} key={story.title} />
                        )
                        ))
                        : (
                            <Skeleton_StoryCard />
                        )
                        }
                    </div>
                    <div className='col-span-1 lg:col-span-4'>
                        <div>
                            <Profile />
                            <StoryWidget />
                            <Categories />
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    )
}

export async function getStaticProps() {
    const stories = (await getStories()) || [];
        return {
            props: {
                stories
            }
    }
}
