import React, { useState } from 'react';
import Head from 'next/head';
import Skeleton_StoryCard from '../../components/Skeletons/Skeleton_StoryCard/Skeleton_StoryCard';
import { StoryCard, StoryWidget, Categories, Welcome } from '../../components';
import { Layout } from '../../components';
import data  from '../../data';

export default function HomePage() {

    const stories = data.data_stories;
    const traveler = data.data_traveler[0];

    return (
        <Layout>
            <div className="container mx-auto px-10 mb-8">
                <Head>
                    <title>My Travel Story App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
                    <div className='col-span-1 lg:col-span-8'>
                        {stories? (
                        stories.map((story) => (
                            <StoryCard story={story} traveler={traveler} key={story.title} />
                        )
                        ))
                        : (
                            <Skeleton_StoryCard />
                        )
                        }
                    </div>
                    <div className='col-span-1 lg:col-span-4'>
                        <div>
                            <Welcome />
                            <StoryWidget />
                            <Categories />
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    )
}

// export async function getStaticProps() {
//     const stories = (await GET_ALL_STORIES()) || [];
//     const traveler = (await GET_TRAVELER()) || [];

//         return {
//             props: {
//                 stories, traveler
//             }
//     }
// }
